services:
  postgres:
    image: postgres:14
    container_name: adform_warehouse
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U adform_user -d adform_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - adform_network # Added this network configuration

  pyspark_processor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: adform_spark
    volumes:
      - ../raw_data:/app/raw_data
      - ../output:/app/output
      - ../logs:/app/logs
      - ../hadoop:/app/hadoop
      - ../:/app # Mount application code for live updates
    environment:
      - PYTHONPATH=/app
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - adform_network

networks:
  adform_network:
    driver: bridge

volumes:
  postgres_data:
    name: adform_postgres_data
